### ISSUE TITLE
咨询B550主板具体型号

### ISSUE THREAD

**Issue by liucxu** [wdongxv/AMD_B550_3900X_RX5500XT_OpenCore_EFI#1]
hi wdongxv，我的CPU&GPU型号与你完全一致，现在主板还没确定，想咨询下你的B550主板的具体型号，能麻烦告知吗，谢谢

**Comment by wdongxv** [comment]
只要是B550应该区别不大。我的是这一款：技嘉 B550M AORUS PRO
